#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.13f1_83fbdcd35118"
#define UNITY_VERSION_FULL_NICE "2018.2.13f1 (83fbdcd35118)"
#define UNITY_VERSION_BLD 8649692
#define UNITY_VERSION_DATE 1539258768
#define UNITY_VERSION_WIN "2018.2.13.8649692"
#define UNITY_VERSION_BRANCH "2018.2/release"
